### ISSUE TITLE
how can I get the data needed to run the program?

### ISSUE THREAD

**Issue by Jacky1y** [robinesp/TextAnomalyDetectionWithVAE#1]
Hi Robin,
without Drive file, I cann't run the program.
can you provide the file?
Thanks.

**Comment by robinesp** [comment]
Hi Jacky,
sorry but the data I used is not available for privacy reasons.
The code should work equally well on any other public text dataset.

**Comment by Jacky1y** [comment]
Got it.
Thanks.
